SOURCES := ${wildcard sources/*.cc}

main: base.o ai.o air.o bike.o car.o character.o entity.o land.o npc.o otherplayer.o particle.o player.o train.o vehicle.o water.otherplayer
	g++ main.cc

all: 
	g++ ${SOURCES}